#!/bin/bash

jq --raw-input '.|split(" ")' example

echo 'xxxxxxx'


# jq --raw-input '.|split(" ") |reduce .[] as $i ({}; .[$i.name] = $i)   ' example

jq --raw-input '
  . |
  split(" ") |
  reduce . as $i ({}; .["original"] = $i) |
  reduce . as $i (.; .["hand"] = $i.original[0]) |
  reduce . as $i (.; .["bid"] = $i.original[1]) |
  reduce (.bid|tonumber) as $i (.; .["bid"] = $i) |
  #reduce (.hand|split("")) as $chars (.; .["point_1_00_00_00_00"] = ($chars[0]|sub("T";"10"))) |
  reduce . as $i (.; .["points_map"] = {"A":50,"K":40,"Q":30,"J":1,"T":10,"9":9,"8":8,"7":7,"6":6,"5":5,"4":4,"3":3,"2":2}) |
  reduce (.hand|split("")[0]) as $first (.; .["point_1_00_00_00_00"] = (.["points_map"][$first])) |
  reduce (.hand|split("")[1]) as $second (.; .["point_1_00_00_00"] = (.["points_map"][$second])) |
  reduce (.hand|split("")[2]) as $third (.; .["point_1_00_00"] = (.["points_map"][$third])) |
  reduce (.hand|split("")[3]) as $fourth (.; .["point_1_00"] = (.["points_map"][$fourth])) |
  reduce (.hand|split("")[4]) as $fifth (.; .["point_1"] = (.["points_map"][$fifth])) |
  reduce (.hand) as $hand (.; .["hand_score"] = (
    $hand|
    split("")|sort|join("")|
    sub("(AAAAA|KKKKK|QQQQQ|JJJJJ|TTTTT|99999|88888|77777|66666|55555|44444|33333|22222)";"a")|
    sub("(AAAA|KKKK|QQQQ|TTTT|9999|8888|7777|6666|5555|4444|3333|2222)";"b")|
    sub("(AAA|KKK|QQQ|TTT|999|888|777|666|555|444|333|222)";"c")|
    gsub("(AA|KK|QQ|TT|99|88|77|66|55|44|33|22)";"d")|
    gsub("(A|K|Q|T|9|8|7|6|5|4|3|2)";"x")|

    split("")|sort|join("")|

    sub("JJJJx";"a")| # high to quin
    sub("JJJxx";"b")| # high to quad
    sub("JJxxx";"c")| # high to triple
    sub("Jxxxx";"d")| # high to pair
    sub("xxxxx";"e")| # high card
    gsub("x";"")|     # clear trailing x

    sub("Jb";"a")| # quad to quin
    sub("JJc";"a")| # triple to quin
    sub("Jc";"b")| # triple to quad
    sub("Jdd";"f")| # two pair to full house
    sub("dd";"g")| # two pair

    sub("JJJd";"a")| # pair to quin
    sub("JJd";"b")| # pair to quad
    sub("Jd";"c")| # pair to triple
    sub("JJJJe";"a")| # high to quin
    sub("JJJe";"b")| # high to quad
    sub("JJe";"c")| # high to triple
    sub("Je";"d")| # high to pair

    sub("cd";"f")| # triple, pair
    # sub("dc";"f")| sorted, this doesnt occur
    .
  )) |
  reduce (.hand_score) as $hand_score (.; .["point_1_00_00_00_00_00"] = (
    $hand_score|
      sub("a";"90")|         # sub("__quin__";"90")|
      sub("b";"80")|         # sub("__quad__";"80")|
      sub("f";"70")|         # sub("__full_house__";"70")|
      sub("c";"60")|         # sub("__triple__";"60")|
      sub("g";"50")|         # sub("__pair____pair__";"50")|
      sub("d";"40")|         # sub("__pair__";"40")|
      sub("e";"30")|         # sub("__high_card__";"30")|
    tonumber
  )) |
  reduce . as $play (.; .["score"] = (
    (10000000000 * $play.point_1_00_00_00_00_00) +
    (100000000   * $play.point_1_00_00_00_00) +
    (1000000     * $play.point_1_00_00_00) +
    (10000       * $play.point_1_00_00) +
    (100         * $play.point_1_00) +
    (1           * $play.point_1)
  )) |
  . ' input | jq -s '
 sort_by(.score) |
  to_entries | map(.multiplier = (.key+1)) |
  to_entries | map(.full_score = (.value.value.bid * .value.multiplier)) |
  to_entries | map(.value.full_score) |
  add |
 .
'
